[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Maria Batrakova <simmura@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "~1.22.2"
opencv-python = "~4.5.5"
tensorflow = "~2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
