[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Maria Batrakova <simmura@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.7"
numpy = "empty"
opencv-python = "~4.5.5"
tensorflow = "~2.8.0"

[tool.poetry.dev-dependencies]

