# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI for a Python package build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing poetry
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        pip install poetry
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r requirements_prod.txt
        pip install -e .
    - name: Run style checks
      run: |
        pre-commit install
        pre-commit run -a
        
    - name: Test with pytest
      working-directory: ./demo
      run: |
        pytest

    - name: Build the package
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
        
    - name: Commit built files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -a -m'[bot] update a version of package' --allow-empty && git push -f
        
